from typing import Dict, List, Optional
from enum import Enum
from dataclasses import dataclass

class Platform(Enum):
    TWITTER = "twitter"
    LINKEDIN = "linkedin"
    DISCORD = "discord"
    BLOG = "blog"

class Tone(Enum):
    PROFESSIONAL = "professional"
    CASUAL = "casual"
    WITTY = "witty"  # The Loki touch
    TECHNICAL = "technical"

@dataclass
class PromptContext:
    topic: str
    audience: Optional[str] = None
    goal: Optional[str] = None
    constraints: Optional[List[str]] = None
    keywords: Optional[List[str]] = None

class PromptFactoryService:
    """
    V1.2 Prompt Factory Service
    Combines creative flair (Loki) with structural precision (Friday).
    """
    VERSION = "1.2"

    def __init__(self):
        self._templates = self._load_templates()

    def _load_templates(self) -> Dict[Platform, Dict[Tone, str]]:
        # V1.2 Templates with Loki's influence
        return {
            Platform.TWITTER: {
                Tone.PROFESSIONAL: (
                    "Draft a professional tweet about {topic}. "
                    "Keep it under 280 chars. Focus on value and insight. "
                    "Goal: {goal}. Keywords: {keywords}."
                ),
                Tone.WITTY: (
                    "Write a tweet about {topic} that pops. "
                    "Use a witty, slightly mischievous tone (Loki style). "
                    "Make them stop scrolling. Max 280 chars. "
                    "Goal: {goal}."
                ),
                Tone.TECHNICAL: (
                    "Create a technical tweet explaining {topic}. "
                    "Be precise, use code snippets if relevant (pseudo). "
                    "Target audience: {audience}."
                )
            },
            Platform.LINKEDIN: {
                Tone.PROFESSIONAL: (
                    "Write a LinkedIn post about {topic}. "
                    "Structure: Hook -> Insight -> Actionable Advice -> Conclusion. "
                    "Tone: Professional but engaging. Audience: {audience}."
                ),
                Tone.WITTY: (
                    "Draft a LinkedIn post on {topic} that breaks the corporate mold. "
                    "Use humor and sharp wit. Challenge conventional wisdom. "
                    "Goal: {goal}."
                )
            },
            Platform.DISCORD: {
                Tone.CASUAL: (
                    "Write a Discord announcement for {topic}. "
                    "Use emojis, keep it hyped but clear. "
                    "Audience: Community members."
                )
            }
        }

    def create_prompt(self, platform: str, tone: str, context: PromptContext) -> str:
        """
        Generates a tailored prompt based on platform, tone, and context.
        """
        try:
            plat_enum = Platform(platform.lower())
            tone_enum = Tone(tone.lower())
        except ValueError:
            # Fallback or robust error handling
            return f"Error: Invalid platform '{platform}' or tone '{tone}'. Supported: {[p.value for p in Platform]}, {[t.value for t in Tone]}"

        template_group = self._templates.get(plat_enum, {})
        template = template_group.get(tone_enum)

        if not template:
            # Fallback for V1.2 generic generation
            template = (
                f"Write a piece of content for {platform} about {{topic}}. "
                f"Tone: {tone}. Context: {{goal}}."
            )

        # Format variable parts
        keywords_str = ", ".join(context.keywords) if context.keywords else "None"
        constraints_str = ", ".join(context.constraints) if context.constraints else "None"
        
        prompt = template.format(
            topic=context.topic,
            audience=context.audience or "General Audience",
            goal=context.goal or "Engagement",
            keywords=keywords_str,
            constraints=constraints_str
        )

        # V1.2 Enhancements: Meta-instructions for the LLM consuming this prompt
        meta_instructions = (
            "\n\n[System Note: This is generated by PromptFactory V1.2. "
            "Ensure high entropy and low predictability in the creative output.]"
        )
        
        return prompt + meta_instructions

    def get_version(self) -> str:
        return self.VERSION

# Self-test if run directly
if __name__ == "__main__":
    factory = PromptFactoryService()
    ctx = PromptContext(topic="AI Agents", goal="Explain the future", keywords=["autonomous", "coding"])
    print(f"--- Prompt Factory V{factory.get_version()} Test ---")
    print(factory.create_prompt("twitter", "witty", ctx))
